services:
  postgres:
    image: postgres:16-alpine
    container_name: mydreamtesla-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: mydreamtesla
      POSTGRES_PASSWORD: mydreamtesla
      POSTGRES_DB: mydreamtesla
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
