import dotenv from 'dotenv';
import { eq } from 'drizzle-orm';
import { getDb } from '../src/db/index.js';
import { teslaModel, vehicle } from '../src/db/schema.js';

dotenv.config();

const miToKm = (mi: number) => Math.round(mi * 1.60934);
const mphToKmh = (mph: number) => Math.round(mph * 1.60934);

const TESLA_MODELS = [
  {
    name: 'Model 3',
    slug: 'model-3',
    tagline: 'The benchmark electric sedan',
    description:
      'Tesla Model 3 is the best-selling electric car of all time. Available in Standard Range, Long Range, and Performance trims, it offers an exceptional blend of range, performance, and value.',
    bodyType: 'Sedan',
    productionStart: 2017,
    isActive: true,
    sortOrder: 1,
    seoTitle: 'Tesla Model 3 — All Years & Trims | MyDreamTesla',
    seoDescription:
      'Compare every Tesla Model 3 from 2017 to 2025. Specs, pricing, range, and performance for all trims including Highland.',
  },
  {
    name: 'Model Y',
    slug: 'model-y',
    tagline: 'The versatile electric SUV',
    description:
      'Tesla Model Y is the best-selling electric vehicle in the world. This compact SUV offers generous cargo space, optional third-row seating, and available AWD — making it the practical choice for families and adventurers alike.',
    bodyType: 'SUV',
    productionStart: 2020,
    isActive: true,
    sortOrder: 2,
    seoTitle: 'Tesla Model Y — All Years & Trims | MyDreamTesla',
    seoDescription:
      'Compare every Tesla Model Y from 2020 to 2025. Specs, pricing, range, cargo space, and towing capacity for all trims including Juniper.',
  },
  {
    name: 'Model S',
    slug: 'model-s',
    tagline: 'The flagship luxury sedan',
    bodyType: 'Sedan',
    productionStart: 2012,
    isActive: false,
    sortOrder: 3,
  },
  {
    name: 'Model X',
    slug: 'model-x',
    tagline: 'The luxury electric SUV',
    bodyType: 'SUV',
    productionStart: 2015,
    isActive: false,
    sortOrder: 4,
  },
  {
    name: 'Cybertruck',
    slug: 'cybertruck',
    tagline: 'The electric pickup truck',
    bodyType: 'Truck',
    productionStart: 2023,
    isActive: false,
    sortOrder: 5,
  },
  {
    name: 'Semi',
    slug: 'semi',
    tagline: 'The electric semi truck',
    bodyType: 'Semi',
    productionStart: 2022,
    isActive: false,
    sortOrder: 6,
  },
  {
    name: 'Roadster',
    slug: 'roadster',
    tagline: 'The next generation supercar',
    bodyType: 'Roadster',
    productionStart: 2008,
    productionEnd: 2012,
    isActive: false,
    sortOrder: 7,
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// ALL TESLA MODEL 3 TRIMS — 2017 to 2025
// Sources: Tesla press releases, EPA ratings, Motortrend, Car and Driver tests
// ─────────────────────────────────────────────────────────────────────────────
const VEHICLES = [
  // ── 2017 ──────────────────────────────────────────────────────────────────
  // Only the Long Range RWD was delivered in 2017 (limited rollout to employees)
  {
    title: '2017 Tesla Model 3 Long Range RWD',
    slug: 'model-3-2017-long-range-rwd',
    modelSlug: 'model-3',
    year: 2017,
    trimName: 'Long Range',
    driveType: 'RWD',
    basePriceMSRP: 44000,
    destinationFee: 1200,
    federalTaxCredit: 7500,
    effectivePrice: 37700,
    rangeEPA: 310,
    acceleration060: '5.1',
    topSpeed: 140,
    horsepower: 258,
    torque: 307,
    batteryCapacity: '75',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3549,
    mpge: 130,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'First Model 3 production year. Initial deliveries were Long Range RWD only, limited to employee/early reservation holders. Introduced Tesla\'s mass-market EV with a 15.4" touchscreen, minimalist interior, and over-the-air updates.',
    prosAndCons: {
      pros: [
        'Revolutionary minimalist interior',
        '310-mile EPA range',
        'Fast OTA software updates',
        'Low center of gravity handling',
      ],
      cons: [
        'Production limited to Long Range only',
        'No front trunk volume yet optimized',
        'Build quality inconsistencies in early units',
        'No rear-view camera standard',
      ],
    },
  },

  // ── 2018 ──────────────────────────────────────────────────────────────────
  {
    title: '2018 Tesla Model 3 Long Range RWD',
    slug: 'model-3-2018-long-range-rwd',
    modelSlug: 'model-3',
    year: 2018,
    trimName: 'Long Range',
    driveType: 'RWD',
    basePriceMSRP: 49000,
    destinationFee: 1200,
    federalTaxCredit: 7500,
    effectivePrice: 42700,
    rangeEPA: 310,
    acceleration060: '5.1',
    topSpeed: 140,
    horsepower: 258,
    torque: 307,
    batteryCapacity: '75',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3549,
    mpge: 130,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Full production ramp-up. Autopilot hardware 2.5 standard. Mid Range RWD variant briefly available. Dual Motor AWD and Performance variants introduced late 2018.',
    prosAndCons: {
      pros: [
        'Full production ramp achieved',
        'Dual motor variants added',
        'Enhanced Autopilot available',
        'Strong resale value',
      ],
      cons: [
        'Price higher than originally promised',
        'Standard Range not yet available',
        'Some panel gap issues',
        'No spare tire',
      ],
    },
  },
  {
    title: '2018 Tesla Model 3 Mid Range RWD',
    slug: 'model-3-2018-mid-range-rwd',
    modelSlug: 'model-3',
    year: 2018,
    trimName: 'Mid Range',
    driveType: 'RWD',
    basePriceMSRP: 46000,
    destinationFee: 1200,
    federalTaxCredit: 7500,
    effectivePrice: 39700,
    rangeEPA: 264,
    acceleration060: '5.6',
    topSpeed: 125,
    horsepower: 225,
    torque: 243,
    batteryCapacity: '62',
    superchargerRateMax: 120,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3450,
    mpge: 136,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Brief option bridging the gap between Standard and Long Range. Discontinued in 2019.',
    prosAndCons: {
      pros: [
        'Good range at lower price point',
        'Eligible for full federal tax credit',
        'Lighter weight than Long Range',
      ],
      cons: [
        'Discontinued — no parts ecosystem',
        'Lower top speed than Long Range',
        'Slower Supercharging',
        'Limited production numbers',
      ],
    },
  },
  {
    title: '2018 Tesla Model 3 Performance AWD',
    slug: 'model-3-2018-performance-awd',
    modelSlug: 'model-3',
    year: 2018,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 64000,
    destinationFee: 1200,
    federalTaxCredit: 7500,
    effectivePrice: 57700,
    rangeEPA: 310,
    acceleration060: '3.5',
    topSpeed: 155,
    horsepower: 450,
    torque: 471,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3862,
    mpge: 116,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'First dual-motor Performance variant. Track Mode available via OTA. Sport brakes and lowered suspension standard.',
    prosAndCons: {
      pros: [
        '3.5s 0-60 mph',
        '155 mph top speed',
        'Track Mode included',
        'All-weather AWD traction',
      ],
      cons: [
        'Significantly higher price',
        'Lower efficiency than standard',
        'Firmer ride quality',
        'No original full federal tax credit in late 2018',
      ],
    },
  },

  // ── 2019 ──────────────────────────────────────────────────────────────────
  {
    title: '2019 Tesla Model 3 Standard Range Plus RWD',
    slug: 'model-3-2019-standard-range-plus-rwd',
    modelSlug: 'model-3',
    year: 2019,
    trimName: 'Standard Range Plus',
    driveType: 'RWD',
    basePriceMSRP: 37990,
    destinationFee: 1200,
    federalTaxCredit: 3750,
    effectivePrice: 35490,
    rangeEPA: 240,
    acceleration060: '5.3',
    topSpeed: 140,
    horsepower: 225,
    torque: 243,
    batteryCapacity: '50',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3380,
    mpge: 141,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'First sub-$40k Model 3. Tesla halved the federal tax credit now applies at 50% ($3,750). Standard Range (non-Plus) briefly offered online-only but discontinued same year.',
    prosAndCons: {
      pros: [
        'Most affordable Model 3 ever sold',
        'Lightest variant for efficiency',
        '240-mile range for daily commutes',
        'Available in more colors',
      ],
      cons: [
        'Partial federal tax credit only ($3,750)',
        'No wood interior trim',
        'Slower acceleration than Long Range',
        'Smaller battery less suitable for road trips',
      ],
    },
  },
  {
    title: '2019 Tesla Model 3 Long Range AWD',
    slug: 'model-3-2019-long-range-awd',
    modelSlug: 'model-3',
    year: 2019,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 47990,
    destinationFee: 1200,
    federalTaxCredit: 3750,
    effectivePrice: 45490,
    rangeEPA: 325,
    acceleration060: '4.4',
    topSpeed: 145,
    horsepower: 346,
    torque: 389,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 121,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Updated to AWD only for Long Range (RWD Long Range phased out). EPA range bumped to 325 miles. V3 Supercharging support added (250kW peak).',
    prosAndCons: {
      pros: [
        '325-mile EPA range',
        'AWD all-weather traction',
        '250kW V3 Supercharging',
        'Best balance of range and performance',
      ],
      cons: [
        'Partial tax credit ($3,750)',
        'Heavier than RWD variants',
        'Higher price than Standard Range',
        'Reduced rear cargo slightly',
      ],
    },
  },
  {
    title: '2019 Tesla Model 3 Performance AWD',
    slug: 'model-3-2019-performance-awd',
    modelSlug: 'model-3',
    year: 2019,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 56990,
    destinationFee: 1200,
    federalTaxCredit: 3750,
    effectivePrice: 54490,
    rangeEPA: 322,
    acceleration060: '3.2',
    topSpeed: 162,
    horsepower: 450,
    torque: 471,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 116,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Track Mode V2 added via OTA. Performance Upgrade package (carbon spoiler, lowered suspension, 20" Uberturbine wheels) available as add-on.',
    prosAndCons: {
      pros: [
        '3.2s 0-60 mph',
        '162 mph top speed',
        'Track Mode for circuit use',
        '322-mile EPA range',
      ],
      cons: [
        'Partial federal tax credit only',
        'Firm sport suspension',
        'Higher tire wear on track',
        '20" wheels reduce ride comfort',
      ],
    },
  },

  // ── 2020 ──────────────────────────────────────────────────────────────────
  {
    title: '2020 Tesla Model 3 Standard Range Plus RWD',
    slug: 'model-3-2020-standard-range-plus-rwd',
    modelSlug: 'model-3',
    year: 2020,
    trimName: 'Standard Range Plus',
    driveType: 'RWD',
    basePriceMSRP: 37990,
    destinationFee: 1200,
    federalTaxCredit: 1875,
    effectivePrice: 36490,
    rangeEPA: 250,
    acceleration060: '5.3',
    topSpeed: 140,
    horsepower: 225,
    torque: 243,
    batteryCapacity: '50',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3380,
    mpge: 141,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Range improved to 250 miles. Federal tax credit further reduced to $1,875 (final year of US credit). LFP battery chemistry introduced for Standard Range. Sentry Mode standard.',
    prosAndCons: {
      pros: [
        '250-mile range',
        'LFP battery can charge to 100% daily',
        'Sentry Mode included',
        'Improved build quality vs early production',
      ],
      cons: [
        'Minimal federal tax credit ($1,875)',
        'Slower acceleration vs AWD',
        'No heated rear seats standard',
        'Steel wheels on base',
      ],
    },
  },
  {
    title: '2020 Tesla Model 3 Long Range AWD',
    slug: 'model-3-2020-long-range-awd',
    modelSlug: 'model-3',
    year: 2020,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 46990,
    destinationFee: 1200,
    federalTaxCredit: 1875,
    effectivePrice: 45490,
    rangeEPA: 358,
    acceleration060: '4.2',
    topSpeed: 145,
    horsepower: 351,
    torque: 389,
    batteryCapacity: '82',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 130,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Major range jump to 358 miles (best in class for sedan at the time). Updated battery pack. 0-60 improved to 4.2s.',
    prosAndCons: {
      pros: [
        '358-mile EPA range — class-leading',
        '4.2s 0-60 mph',
        'V3 Supercharging 250kW',
        'Premium interior standard',
      ],
      cons: [
        'Federal tax credit nearly phased out',
        'Premium over Standard Range',
        'Slightly reduced cargo with larger battery',
        'Heavier curb weight',
      ],
    },
  },
  {
    title: '2020 Tesla Model 3 Performance AWD',
    slug: 'model-3-2020-performance-awd',
    modelSlug: 'model-3',
    year: 2020,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 54990,
    destinationFee: 1200,
    federalTaxCredit: 1875,
    effectivePrice: 53490,
    rangeEPA: 315,
    acceleration060: '3.1',
    topSpeed: 162,
    horsepower: 450,
    torque: 471,
    batteryCapacity: '82',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 116,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      '0-60 improved to 3.1s. Larger 82 kWh battery. Track Mode V2 via OTA. Updated brake hardware.',
    prosAndCons: {
      pros: [
        '3.1s 0-60 mph',
        'Class-leading EV performance',
        'Track Mode V2',
        'Carbon fiber spoiler option',
      ],
      cons: [
        'No longer qualifies for federal tax credit',
        'Lower range than Long Range',
        'Firm ride',
        'Tire wear on performance tires',
      ],
    },
  },

  // ── 2021 ──────────────────────────────────────────────────────────────────
  {
    title: '2021 Tesla Model 3 Standard Range Plus RWD',
    slug: 'model-3-2021-standard-range-plus-rwd',
    modelSlug: 'model-3',
    year: 2021,
    trimName: 'Standard Range Plus',
    driveType: 'RWD',
    basePriceMSRP: 39990,
    destinationFee: 1200,
    rangeEPA: 263,
    acceleration060: '5.8',
    topSpeed: 140,
    horsepower: 283,
    torque: 307,
    batteryCapacity: '50',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3582,
    mpge: 141,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Rear motor upgraded to more efficient permanent magnet motor. Range increased to 263 miles. Heated rear seats added to Standard Range. US federal tax credit no longer available.',
    prosAndCons: {
      pros: [
        'Heated rear seats standard',
        '263-mile range',
        'Improved motor efficiency',
        'Mature software/OTA system',
      ],
      cons: [
        'No federal tax credit',
        '0-60 slightly slower than prior year due to motor retuning',
        'Price increased to $39,990',
        'Still no ventilated seats',
      ],
    },
  },
  {
    title: '2021 Tesla Model 3 Long Range AWD',
    slug: 'model-3-2021-long-range-awd',
    modelSlug: 'model-3',
    year: 2021,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 48990,
    destinationFee: 1200,
    rangeEPA: 358,
    acceleration060: '4.2',
    topSpeed: 145,
    horsepower: 351,
    torque: 389,
    batteryCapacity: '82',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 130,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Largely carry-over from 2020. Price adjustment. OTA improvements including improved regenerative braking and better energy recovery.',
    prosAndCons: {
      pros: [
        'Best-in-class 358-mile range',
        'Consistent 4.2s 0-60',
        'Mature Autopilot hardware',
        'Excellent long-distance capability',
      ],
      cons: [
        'No federal tax credit',
        'Interior unchanged since launch',
        'No heads-up display',
        'Charging speed not upgraded',
      ],
    },
  },
  {
    title: '2021 Tesla Model 3 Performance AWD',
    slug: 'model-3-2021-performance-awd',
    modelSlug: 'model-3',
    year: 2021,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 56990,
    destinationFee: 1200,
    rangeEPA: 315,
    acceleration060: '3.1',
    topSpeed: 162,
    horsepower: 450,
    torque: 471,
    batteryCapacity: '82',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 116,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Track Mode V2 improvements via OTA. Carry-over specs from 2020. Best performance sedan value on the market.',
    prosAndCons: {
      pros: [
        '3.1s 0-60 — supercar pace',
        'Track Mode for circuit days',
        '315-mile range with AWD',
        'Stiff and precise handling',
      ],
      cons: [
        'Over $57,000 before options',
        'Firm daily ride',
        'No HUD',
        'No ventilated seats',
      ],
    },
  },

  // ── 2022 — MAJOR INTERIOR REFRESH ────────────────────────────────────────
  {
    title: '2022 Tesla Model 3 Standard Range Plus RWD',
    slug: 'model-3-2022-standard-range-plus-rwd',
    modelSlug: 'model-3',
    year: 2022,
    trimName: 'Standard Range Plus',
    driveType: 'RWD',
    basePriceMSRP: 46990,
    destinationFee: 1390,
    rangeEPA: 272,
    acceleration060: '5.8',
    topSpeed: 140,
    horsepower: 283,
    torque: 307,
    batteryCapacity: '50',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3582,
    mpge: 141,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Major interior overhaul: new center console, USB-C ports, updated ambient lighting, chrome delete exterior. Exterior refreshed with sharper headlights. Price increased due to supply chain pressures.',
    prosAndCons: {
      pros: [
        'Significantly improved interior quality',
        'USB-C charging everywhere',
        'Refreshed exterior design',
        'Better build quality than early production',
      ],
      cons: [
        'Significant price increase vs 2021',
        'Still no federal tax credit',
        'No physical buttons added',
        'Price inflation from supply chain',
      ],
    },
  },
  {
    title: '2022 Tesla Model 3 Long Range AWD',
    slug: 'model-3-2022-long-range-awd',
    modelSlug: 'model-3',
    year: 2022,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 55990,
    destinationFee: 1390,
    rangeEPA: 358,
    acceleration060: '4.2',
    topSpeed: 145,
    horsepower: 358,
    torque: 389,
    batteryCapacity: '82',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 130,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Same interior refresh as Standard Range. Horsepower increased to 358hp. Range maintained at 358 miles despite price increase.',
    prosAndCons: {
      pros: [
        'Updated interior with new console',
        '358-mile range',
        'Improved exterior styling',
        'Strong software maturity',
      ],
      cons: [
        '$56k base — expensive vs 2020',
        'No federal tax credit',
        'Supply chain delays affected availability',
        'Interior refresh not as dramatic as Highland later',
      ],
    },
  },
  {
    title: '2022 Tesla Model 3 Performance AWD',
    slug: 'model-3-2022-performance-awd',
    modelSlug: 'model-3',
    year: 2022,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 62990,
    destinationFee: 1390,
    rangeEPA: 315,
    acceleration060: '3.1',
    topSpeed: 162,
    horsepower: 450,
    torque: 471,
    batteryCapacity: '82',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 116,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Interior refresh package. Price reached $63k — highest for non-Plaid Model 3. Performance credentials unchanged but value proposition debated.',
    prosAndCons: {
      pros: [
        'Interior refresh brings premium feel',
        '3.1s 0-60 unchanged',
        'Track Mode remains excellent',
        'Better build quality',
      ],
      cons: [
        '$63k — highest M3 Performance price ever',
        'No performance gains over 2021',
        'Some buyers waited for price drops',
        'No federal tax credit',
      ],
    },
  },

  // ── 2023 ──────────────────────────────────────────────────────────────────
  {
    title: '2023 Tesla Model 3 Standard Range Plus RWD',
    slug: 'model-3-2023-standard-range-plus-rwd',
    modelSlug: 'model-3',
    year: 2023,
    trimName: 'Standard Range Plus',
    driveType: 'RWD',
    basePriceMSRP: 40240,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 32740,
    rangeEPA: 272,
    acceleration060: '6.1',
    topSpeed: 140,
    horsepower: 283,
    torque: 307,
    batteryCapacity: '50',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 3582,
    mpge: 141,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'IRA Inflation Reduction Act reinstated $7,500 federal tax credit for US buyers. Tesla cut prices dramatically — Model 3 RWD dropped from $47k to $40k. Effective price under $33k with credit.',
    prosAndCons: {
      pros: [
        'Full $7,500 federal tax credit restored',
        'Lowest effective price in years ($32,740)',
        'Good 272-mile range for commuting',
        'Mature, reliable platform',
      ],
      cons: [
        '0-60 slowed to 6.1s — slowest Model 3',
        'Last year of pre-Highland exterior',
        'Interior same as 2022',
        'Some uncertainty before Highland launch',
      ],
    },
  },
  {
    title: '2023 Tesla Model 3 Long Range AWD',
    slug: 'model-3-2023-long-range-awd',
    modelSlug: 'model-3',
    year: 2023,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 47240,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 39740,
    rangeEPA: 358,
    acceleration060: '4.2',
    topSpeed: 145,
    horsepower: 358,
    torque: 389,
    batteryCapacity: '82',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 130,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Price cut to $47,240 with full $7,500 credit — effective $39,740. Best value Long Range Model 3 ever offered. Long Range AWD briefly unavailable late 2023 ahead of Highland.',
    prosAndCons: {
      pros: [
        '$7,500 federal tax credit',
        'Effective price ~$39,740',
        '358-mile range class-leading',
        'V3 Supercharging 250kW',
      ],
      cons: [
        'Limited availability late 2023 ahead of Highland launch',
        'Pre-Highland exterior about to be replaced',
        'Some buyers held out for Highland',
      ],
    },
  },
  {
    title: '2023 Tesla Model 3 Performance AWD',
    slug: 'model-3-2023-performance-awd',
    modelSlug: 'model-3',
    year: 2023,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 53240,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 45740,
    rangeEPA: 315,
    acceleration060: '3.1',
    topSpeed: 162,
    horsepower: 450,
    torque: 471,
    batteryCapacity: '82',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    displaySize: '15.4"',
    wheelbase: '113.2',
    curbWeight: 4065,
    mpge: 116,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Massive price cut from $62,990 to $53,240. With $7,500 credit, effective price drops to $45,740 — $17k less than 2022. Best performance car value in its class.',
    prosAndCons: {
      pros: [
        '$17k cheaper than 2022 equivalent',
        'Effective price ~$45,740 with credit',
        '3.1s 0-60 — unchanged performance',
        'Track Mode V2',
      ],
      cons: [
        'Performance specs identical to 2021/2022',
        'Pre-Highland exterior',
        'Limited availability as Highland launched',
        'Ride still firm for daily use',
      ],
    },
  },

  // ── 2024 — HIGHLAND FACELIFT ──────────────────────────────────────────────
  {
    title: '2024 Tesla Model 3 Standard Range Plus RWD',
    slug: 'model-3-2024-standard-range-plus-rwd',
    modelSlug: 'model-3',
    year: 2024,
    trimName: 'Standard Range Plus',
    driveType: 'RWD',
    basePriceMSRP: 38990,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 31490,
    rangeEPA: 272,
    acceleration060: '5.8',
    topSpeed: 125,
    horsepower: 271,
    torque: 307,
    batteryCapacity: '60',
    superchargerRateMax: 170,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.2',
    length: '184.8',
    width: '72.8',
    height: '56.8',
    curbWeight: 3862,
    mpge: 138,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Highland facelift: completely redesigned front fascia, full-width light bars front and rear, new ambient lighting inside, rear entertainment screen added, improved NVH, ventilated front seats, 11.5kW onboard charger.',
    prosAndCons: {
      pros: [
        'Completely redesigned inside and out',
        'Rear passenger screen standard',
        'Ventilated front seats',
        'Lower NVH / quieter cabin',
        '$7,500 federal tax credit',
      ],
      cons: [
        'Top speed reduced to 125 mph',
        'Slightly heavier than predecessor',
        'Rear screen adds complexity',
        'Price premium vs 2023',
      ],
    },
  },
  {
    title: '2024 Tesla Model 3 Long Range AWD',
    slug: 'model-3-2024-long-range-awd',
    modelSlug: 'model-3',
    year: 2024,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 45990,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 38490,
    rangeEPA: 341,
    acceleration060: '4.4',
    topSpeed: 125,
    horsepower: 346,
    torque: 389,
    batteryCapacity: '79',
    superchargerRateMax: 250,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.2',
    length: '184.8',
    width: '72.8',
    height: '56.8',
    curbWeight: 4056,
    mpge: 123,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Highland redesign. Range slightly reduced to 341 mi vs 358 mi for prior gen due to aero changes. Improved interior, rear screen, ventilated seats standard.',
    prosAndCons: {
      pros: [
        'Highland redesign — fresh look',
        'Rear screen for passengers',
        'Ventilated front seats',
        'Strong 341-mile range',
        '$7,500 credit',
      ],
      cons: [
        'Range dropped slightly vs 2023 (341 vs 358 mi)',
        'Top speed capped at 125 mph',
        'Heavier than pre-Highland',
        'Higher price than 2023',
      ],
    },
  },
  {
    title: '2024 Tesla Model 3 Performance AWD',
    slug: 'model-3-2024-performance-awd',
    modelSlug: 'model-3',
    year: 2024,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 52990,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 45490,
    rangeEPA: 303,
    acceleration060: '3.1',
    topSpeed: 163,
    horsepower: 510,
    torque: 539,
    batteryCapacity: '79',
    superchargerRateMax: 250,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.2',
    length: '184.8',
    width: '72.8',
    height: '56.8',
    curbWeight: 4090,
    mpge: 112,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Highland Performance: horsepower up from 450 to 510hp, torque up to 539 lb-ft. New two-tone interior option. Carbon fiber elements standard. Track Mode 3.0.',
    prosAndCons: {
      pros: [
        '510hp — most powerful Model 3 ever',
        'Track Mode 3.0',
        'Carbon fiber rear diffuser',
        'New two-tone interior',
        '$7,500 credit + $52,990 base',
      ],
      cons: [
        'Lowest range of Highland lineup (303 mi)',
        'Firm performance suspension',
        'Heavier than predecessors',
        'Performance tires cost more to replace',
      ],
    },
  },

  // ── 2025 — HIGHLAND (CURRENT) ─────────────────────────────────────────────
  {
    title: '2025 Tesla Model 3 Rear-Wheel Drive',
    slug: 'model-3-2025-standard-range-plus-rwd',
    modelSlug: 'model-3',
    year: 2025,
    trimName: 'Rear-Wheel Drive',
    caTrimName: 'Rear-Wheel Drive',
    driveType: 'RWD',
    basePriceMSRP: 38990,
    destinationFee: 1640,
    federalTaxCredit: 7500,
    effectivePrice: 33130,
    rangeEPA: 321,
    acceleration060: '5.8',
    topSpeed: 125,
    horsepower: 271,
    torque: 307,
    batteryCapacity: '60',
    superchargerRateMax: 225,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.2',
    length: '184.8',
    width: '72.8',
    height: '56.8',
    curbWeight: 3862,
    mpge: 138,
    isCurrentModel: true,
    keyChangesFromPriorYear:
      'Minor updates from 2024 Highland. Autopilot hardware refresh with updated AI chip. Destination fee increase. Current US lineup naming displays this trim as Rear-Wheel Drive.',
    prosAndCons: {
      pros: [
        '$7,500 federal tax credit',
        'Effective price ~$33,130',
        'Latest Autopilot hardware',
        'Rear screen for passengers',
        'Ventilated front seats',
      ],
      cons: [
        '321-mile range is below Premium RWD',
        '125 mph top speed',
        'Destination fee increased to $1,640',
        'No HUD option',
      ],
    },
  },
  {
    title: '2025 Tesla Model 3 Premium RWD',
    slug: 'model-3-2025-premium-rwd',
    modelSlug: 'model-3',
    year: 2025,
    trimName: 'Premium RWD',
    caTrimName: 'Long Range RWD',
    driveType: 'RWD',
    rangeEPA: 363,
    acceleration060: '4.9',
    superchargerRateMax: 250,
    caRangeEPAkm: 584,
    caAcceleration0100: '5.2',
    isCurrentModel: true,
    keyChangesFromPriorYear:
      'Added as the long-range single-motor Highland option in the US lineup. Canadian naming commonly maps this trim to Long Range RWD.',
  },
  {
    title: '2025 Tesla Model 3 Premium AWD',
    slug: 'model-3-2025-long-range-awd',
    modelSlug: 'model-3',
    year: 2025,
    trimName: 'Premium AWD',
    caTrimName: 'Long Range AWD',
    driveType: 'AWD',
    basePriceMSRP: 42990,
    destinationFee: 1640,
    federalTaxCredit: 7500,
    effectivePrice: 37130,
    rangeEPA: 346,
    caRangeEPAkm: 550,
    acceleration060: '4.2',
    topSpeed: 125,
    horsepower: 346,
    torque: 389,
    batteryCapacity: '79',
    superchargerRateMax: 250,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.2',
    length: '184.8',
    width: '72.8',
    height: '56.8',
    curbWeight: 4056,
    mpge: 123,
    isCurrentModel: true,
    keyChangesFromPriorYear:
      'Current US lineup naming displays this trim as Premium AWD (CA commonly labels it Long Range AWD). Dual-motor Highland balance remains a sweet spot for many buyers.',
    prosAndCons: {
      pros: [
        '346-mile EPA range',
        '$7,500 credit — effective $37,130',
        'Dual motor AWD for all-weather',
        'Rear screen + ventilated seats',
        'Latest Autopilot hardware',
      ],
      cons: [
        'Premium branding can be confusing vs prior Long Range naming',
        'Top speed 125 mph',
        'Heavier than pre-Highland',
        'No Performance track features',
      ],
    },
  },
  {
    title: '2025 Tesla Model 3 Performance AWD',
    slug: 'model-3-2025-performance-awd',
    modelSlug: 'model-3',
    year: 2025,
    trimName: 'Performance',
    caTrimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 54990,
    destinationFee: 1640,
    federalTaxCredit: 7500,
    effectivePrice: 49130,
    rangeEPA: 309,
    caRangeEPAkm: 478,
    acceleration060: '2.9',
    caAcceleration0100: '3.1',
    topSpeed: 163,
    horsepower: 510,
    caHorsepower: 460,
    torque: 539,
    batteryCapacity: '79',
    superchargerRateMax: 250,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.2',
    length: '184.8',
    width: '72.8',
    height: '56.8',
    curbWeight: 4090,
    mpge: 112,
    isCurrentModel: true,
    keyChangesFromPriorYear:
      '0-60 improved to 2.9s (from 3.1s). Updated Track Mode 3.0. Carbon fiber spoiler standard. Torque vectoring improved.',
    prosAndCons: {
      pros: [
        '2.9s 0-60 — fastest production Model 3 ever',
        '510hp dual motor',
        'Track Mode 3.0 with torque vectoring',
        '$7,500 credit — effective $49,130',
        'Carbon spoiler standard',
      ],
      cons: [
        '309-mile range — lowest in lineup',
        'Firm ride not ideal daily',
        'Over $55k before options',
        'Performance tires add replacement cost',
      ],
    },
  },
  // ═════════════════════════════════════════════════════════════════════════
  // TESLA MODEL Y — 2020 to 2025 (18 vehicles)
  // Sources: Tesla.com, EPA, Car and Driver, MotorTrend, NHTSA
  // ═════════════════════════════════════════════════════════════════════════

  // ── 2020 Model Y ─────────────────────────────────────────────────────────
  {
    title: '2020 Tesla Model Y Long Range AWD',
    slug: 'model-y-2020-long-range-awd',
    modelSlug: 'model-y',
    year: 2020,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 49990,
    destinationFee: 1200,
    rangeEPA: 316,
    acceleration060: '4.8',
    topSpeed: 135,
    horsepower: 384,
    torque: 376,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '68',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4416,
    mpge: 121,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'First Model Y production year. Built on Model 3 platform with raised ride height, hatchback, and optional third-row seating. Deliveries began March 2020.',
    prosAndCons: {
      pros: [
        'Spacious hatchback cargo area',
        'Model 3 platform with SUV practicality',
        '316-mile EPA range',
        'Available third-row seating',
      ],
      cons: [
        'Early production build quality issues',
        'No federal tax credit',
        'Third row cramped for adults',
        'Higher price than Model 3 equivalent',
      ],
    },
  },
  {
    title: '2020 Tesla Model Y Performance AWD',
    slug: 'model-y-2020-performance-awd',
    modelSlug: 'model-y',
    year: 2020,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 59990,
    destinationFee: 1200,
    rangeEPA: 291,
    acceleration060: '3.5',
    topSpeed: 155,
    horsepower: 456,
    torque: 497,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '68',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4416,
    mpge: 111,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'First Model Y Performance. 3.5s 0-60 makes it the fastest SUV in its class. Lowered suspension, 21" Uberturbine wheels, performance brakes.',
    prosAndCons: {
      pros: [
        '3.5s 0-60 — fastest SUV in class',
        '155 mph top speed',
        'Performance brakes and suspension',
        'Practical SUV with supercar acceleration',
      ],
      cons: [
        '291-mile range lower than Long Range',
        'No federal tax credit',
        'Firm ride from performance suspension',
        '21" wheels prone to pothole damage',
      ],
    },
  },

  // ── 2021 Model Y ─────────────────────────────────────────────────────────
  {
    title: '2021 Tesla Model Y Standard Range RWD',
    slug: 'model-y-2021-standard-range-rwd',
    modelSlug: 'model-y',
    year: 2021,
    trimName: 'Standard Range',
    driveType: 'RWD',
    basePriceMSRP: 39990,
    destinationFee: 1200,
    rangeEPA: 244,
    acceleration060: '5.3',
    topSpeed: 135,
    horsepower: 283,
    torque: 310,
    batteryCapacity: '60',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    cargoVolume: '68',
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4100,
    mpge: 129,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Standard Range RWD added mid-2021 at $39,990 — briefly the most affordable Model Y. Discontinued within months as Tesla focused on higher-margin trims.',
    prosAndCons: {
      pros: [
        'Most affordable Model Y ever at $39,990',
        'Lighter RWD for better efficiency',
        '244-mile range for daily commutes',
        'SUV versatility at sedan price',
      ],
      cons: [
        'Discontinued quickly — limited availability',
        'No AWD for winter traction',
        'No towing capability',
        '244-mile range shortest of lineup',
      ],
    },
  },
  {
    title: '2021 Tesla Model Y Long Range AWD',
    slug: 'model-y-2021-long-range-awd',
    modelSlug: 'model-y',
    year: 2021,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 49990,
    destinationFee: 1200,
    rangeEPA: 326,
    acceleration060: '4.8',
    topSpeed: 135,
    horsepower: 384,
    torque: 376,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '68',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4416,
    mpge: 122,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Range increased to 326 miles. Heated steering wheel added. Chrome delete standard. USB-C ports replace USB-A. Production ramped at Fremont and Shanghai.',
    prosAndCons: {
      pros: [
        '326-mile EPA range',
        'Heated steering wheel now standard',
        'Chrome delete for sleeker look',
        'Strong production availability',
      ],
      cons: [
        'No federal tax credit',
        'Price unchanged at $49,990',
        'Interior design mostly carry-over',
        'No ventilated seats',
      ],
    },
  },
  {
    title: '2021 Tesla Model Y Performance AWD',
    slug: 'model-y-2021-performance-awd',
    modelSlug: 'model-y',
    year: 2021,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 59990,
    destinationFee: 1200,
    rangeEPA: 303,
    acceleration060: '3.5',
    topSpeed: 155,
    horsepower: 456,
    torque: 497,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '68',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4416,
    mpge: 111,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Range improved to 303 miles. Same chrome delete and heated steering wheel updates as Long Range. Track Mode available via OTA.',
    prosAndCons: {
      pros: [
        '3.5s 0-60 unchanged',
        'Range improved to 303 miles',
        'Chrome delete standard',
        'Track Mode available',
      ],
      cons: [
        '$59,990 — premium price',
        'No federal tax credit',
        'Firm performance ride',
        '21" wheels reduce range further in cold',
      ],
    },
  },

  // ── 2022 Model Y ─────────────────────────────────────────────────────────
  {
    title: '2022 Tesla Model Y Long Range AWD',
    slug: 'model-y-2022-long-range-awd',
    modelSlug: 'model-y',
    year: 2022,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 65990,
    destinationFee: 1390,
    rangeEPA: 330,
    acceleration060: '4.8',
    topSpeed: 135,
    horsepower: 384,
    torque: 376,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '76',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4398,
    mpge: 122,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Peak pricing year — $65,990 due to supply chain constraints. Range improved to 330 miles. AMD Ryzen infotainment chip replaced Intel Atom. 12V lithium battery replaced lead-acid.',
    prosAndCons: {
      pros: [
        'AMD Ryzen chip — much faster infotainment',
        '330-mile range',
        '12V lithium battery more reliable',
        'Improved build quality from Austin/Berlin plants',
      ],
      cons: [
        'Highest Model Y price ever at $65,990',
        'No federal tax credit',
        'Supply chain delays on delivery',
        'SR trim unavailable',
      ],
    },
  },
  {
    title: '2022 Tesla Model Y Performance AWD',
    slug: 'model-y-2022-performance-awd',
    modelSlug: 'model-y',
    year: 2022,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 69990,
    destinationFee: 1390,
    rangeEPA: 303,
    acceleration060: '3.5',
    topSpeed: 155,
    horsepower: 456,
    torque: 497,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '76',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4416,
    mpge: 111,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Price peaked at $69,990 — most expensive Model Y ever. AMD Ryzen upgrade. Otherwise carry-over Performance specs.',
    prosAndCons: {
      pros: [
        'AMD Ryzen infotainment upgrade',
        '3.5s 0-60 consistent',
        'Track Mode improvements',
        'Strong resale value',
      ],
      cons: [
        '$69,990 — highest MY price ever',
        'No federal tax credit',
        'Performance tires expensive to replace',
        'Long wait times for delivery',
      ],
    },
  },

  // ── 2023 Model Y ─────────────────────────────────────────────────────────
  {
    title: '2023 Tesla Model Y Standard Range RWD',
    slug: 'model-y-2023-standard-range-rwd',
    modelSlug: 'model-y',
    year: 2023,
    trimName: 'Standard Range',
    driveType: 'RWD',
    basePriceMSRP: 43990,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 36490,
    rangeEPA: 260,
    acceleration060: '5.0',
    topSpeed: 135,
    horsepower: 283,
    torque: 310,
    batteryCapacity: '60',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    cargoVolume: '76',
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4100,
    mpge: 129,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'IRA restored $7,500 federal tax credit. Tesla slashed prices — Standard Range returned at $43,990 (was $65k+ for LR in 2022). Effective price ~$36,490.',
    prosAndCons: {
      pros: [
        '$7,500 federal tax credit restored',
        'Effective price ~$36,490',
        'Standard Range returns to lineup',
        'Best SUV value in EV market',
      ],
      cons: [
        '260-mile range shortest in lineup',
        'RWD only — no AWD option at this price',
        'No towing rating on SR',
        'Some buyers waited for Juniper',
      ],
    },
  },
  {
    title: '2023 Tesla Model Y Long Range AWD',
    slug: 'model-y-2023-long-range-awd',
    modelSlug: 'model-y',
    year: 2023,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 50490,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 42990,
    rangeEPA: 330,
    acceleration060: '4.8',
    topSpeed: 135,
    horsepower: 384,
    torque: 376,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '76',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4398,
    mpge: 122,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Price cut from $65,990 to $50,490. With $7,500 credit, effective $42,990 — $23k less than 2022. Best-selling EV in the world this year.',
    prosAndCons: {
      pros: [
        '$7,500 tax credit',
        'Effective price ~$42,990',
        '330-mile range',
        'Best-selling EV globally in 2023',
      ],
      cons: [
        'Pre-Juniper exterior design',
        'Interior unchanged from 2022',
        'Some held out for Juniper refresh',
        'Towing reduces range significantly',
      ],
    },
  },
  {
    title: '2023 Tesla Model Y Performance AWD',
    slug: 'model-y-2023-performance-awd',
    modelSlug: 'model-y',
    year: 2023,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 54490,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 46990,
    rangeEPA: 303,
    acceleration060: '3.5',
    topSpeed: 155,
    horsepower: 456,
    torque: 497,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '76',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4416,
    mpge: 111,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Price dropped from $69,990 to $54,490. With credit, effective $46,990 — $23k less than 2022. Best performance SUV value.',
    prosAndCons: {
      pros: [
        '$23k cheaper than 2022 equivalent',
        'Effective ~$46,990 with credit',
        '3.5s 0-60 unchanged',
        'Track Mode for circuit days',
      ],
      cons: [
        '303-mile range with performance tires',
        'Pre-Juniper design',
        'Firm ride for family SUV',
        '21" wheels impractical in harsh winters',
      ],
    },
  },

  // ── 2024 Model Y ─────────────────────────────────────────────────────────
  {
    title: '2024 Tesla Model Y Standard Range RWD',
    slug: 'model-y-2024-standard-range-rwd',
    modelSlug: 'model-y',
    year: 2024,
    trimName: 'Standard Range',
    driveType: 'RWD',
    basePriceMSRP: 44990,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 37490,
    rangeEPA: 260,
    acceleration060: '5.0',
    topSpeed: 135,
    horsepower: 283,
    torque: 310,
    batteryCapacity: '60',
    superchargerRateMax: 170,
    seatingCapacity: 5,
    cargoVolume: '76',
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4100,
    mpge: 129,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Final year of pre-Juniper design. Minor price increase to $44,990. Suspension tuning refined. Last chance to buy the original Model Y shape.',
    prosAndCons: {
      pros: [
        '$7,500 federal tax credit',
        'Effective price ~$37,490',
        'Proven reliable platform',
        'Mature software ecosystem',
      ],
      cons: [
        '260-mile range unchanged',
        'About to be superseded by Juniper',
        'Pre-Juniper exterior aging',
        'No rear screen or ventilated seats',
      ],
    },
  },
  {
    title: '2024 Tesla Model Y Long Range AWD',
    slug: 'model-y-2024-long-range-awd',
    modelSlug: 'model-y',
    year: 2024,
    trimName: 'Long Range',
    driveType: 'AWD',
    basePriceMSRP: 49990,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 42490,
    rangeEPA: 310,
    acceleration060: '4.8',
    topSpeed: 135,
    horsepower: 384,
    torque: 376,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '76',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4398,
    mpge: 122,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Range reduced to 310 miles (from 330) due to EPA testing changes. Final pre-Juniper Long Range. Price returned to $49,990.',
    prosAndCons: {
      pros: [
        '$7,500 tax credit — effective $42,490',
        '310-mile range',
        '3,500 lb towing capacity',
        'Proven dual-motor AWD system',
      ],
      cons: [
        'Range dropped to 310 mi from 330',
        'About to be replaced by Juniper',
        'Interior showing its age',
        'No rear entertainment screen',
      ],
    },
  },
  {
    title: '2024 Tesla Model Y Performance AWD',
    slug: 'model-y-2024-performance-awd',
    modelSlug: 'model-y',
    year: 2024,
    trimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 52490,
    destinationFee: 1390,
    federalTaxCredit: 7500,
    effectivePrice: 44990,
    rangeEPA: 285,
    acceleration060: '3.5',
    topSpeed: 155,
    horsepower: 456,
    torque: 497,
    batteryCapacity: '75',
    superchargerRateMax: 250,
    seatingCapacity: 5,
    cargoVolume: '76',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4416,
    mpge: 111,
    isCurrentModel: false,
    keyChangesFromPriorYear:
      'Final pre-Juniper Performance. Range adjusted to 285 miles. Price dropped to $52,490. Last Model Y Performance with original exterior design.',
    prosAndCons: {
      pros: [
        '$7,500 credit — effective $44,990',
        '3.5s 0-60',
        'Track Mode included',
        'Strong resale as last pre-Juniper',
      ],
      cons: [
        '285-mile range — lowest of lineup',
        'Juniper successor imminent',
        'Firm ride for daily SUV use',
        'Performance tires costly to replace',
      ],
    },
  },

  // ── 2025 Model Y — JUNIPER REFRESH (CURRENT) ────────────────────────────
  {
    title: '2025 Tesla Model Y Rear-Wheel Drive',
    slug: 'model-y-2025-standard-range-rwd',
    modelSlug: 'model-y',
    year: 2025,
    trimName: 'Rear-Wheel Drive',
    caTrimName: 'Rear-Wheel Drive',
    driveType: 'RWD',
    basePriceMSRP: 44990,
    destinationFee: 1640,
    federalTaxCredit: 7500,
    effectivePrice: 39130,
    rangeEPA: 321,
    caRangeEPAkm: 463,
    acceleration060: '6.8',
    caAcceleration0100: '7.2',
    topSpeed: 135,
    horsepower: 283,
    torque: 310,
    batteryCapacity: '63',
    superchargerRateMax: 225,
    caSuperchargerRateMax: 175,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    cargoVolume: '76',
    groundClearance: '6.6',
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4100,
    mpge: 132,
    isCurrentModel: true,
    keyChangesFromPriorYear:
      'Juniper refresh: completely redesigned front and rear fascia with full-width light bar. New interior with rear passenger screen, ventilated front seats, improved NVH. Current US RWD spec is listed at 321 miles EPA.',
    prosAndCons: {
      pros: [
        'Juniper redesign — fresh exterior and interior',
        'Rear passenger entertainment screen',
        'Ventilated front seats standard',
        '321-mile EPA range',
        '$7,500 federal tax credit',
      ],
      cons: [
        '$44,990 base — same as pre-Juniper',
        'RWD only — no AWD at this price',
        'No towing rating on SR',
        'Destination fee increased to $1,640',
      ],
    },
  },
  {
    title: '2025 Tesla Model Y AWD',
    slug: 'model-y-2025-awd',
    modelSlug: 'model-y',
    year: 2025,
    trimName: 'AWD',
    driveType: 'AWD',
    rangeEPA: 294,
    acceleration060: '4.6',
    superchargerRateMax: 225,
    isCurrentModel: true,
    caAvailable: false,
    keyChangesFromPriorYear:
      'US-market AWD trim in the Juniper lineup. Not currently listed on Tesla Canada.',
  },
  {
    title: '2025 Tesla Model Y Premium RWD',
    slug: 'model-y-2025-premium-rwd',
    modelSlug: 'model-y',
    year: 2025,
    trimName: 'Premium RWD',
    driveType: 'RWD',
    rangeEPA: 357,
    acceleration060: '5.4',
    superchargerRateMax: 250,
    isCurrentModel: true,
    caAvailable: false,
    keyChangesFromPriorYear:
      'US-market long-range single-motor Juniper trim. Not currently listed on Tesla Canada.',
  },
  {
    title: '2025 Tesla Model Y Premium AWD',
    slug: 'model-y-2025-long-range-awd',
    modelSlug: 'model-y',
    year: 2025,
    trimName: 'Premium AWD',
    caTrimName: 'Premium AWD',
    driveType: 'AWD',
    basePriceMSRP: 49990,
    destinationFee: 1640,
    federalTaxCredit: 7500,
    effectivePrice: 44130,
    rangeEPA: 327,
    caRangeEPAkm: 542,
    acceleration060: '4.6',
    caAcceleration0100: '5.0',
    topSpeed: 135,
    horsepower: 393,
    torque: 389,
    batteryCapacity: '79',
    superchargerRateMax: 250,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    cargoVolume: '76',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4398,
    mpge: 124,
    isCurrentModel: true,
    keyChangesFromPriorYear:
      'Juniper refresh Premium AWD with rear screen, ventilated seats, updated Autopilot hardware, and premium-range positioning in the 2025 US lineup.',
    prosAndCons: {
      pros: [
        '327-mile EPA range',
        '4.6s 0-60 performance',
        'Juniper exterior and interior refresh',
        'Rear screen + ventilated seats',
        '3,500 lb towing capacity',
      ],
      cons: [
        '$49,990 base + $1,640 destination',
        'Effective price $44,130 after credit',
        'Top speed still 135 mph',
        'Heavier than pre-Juniper',
      ],
    },
  },
  {
    title: '2025 Tesla Model Y Performance AWD',
    slug: 'model-y-2025-performance-awd',
    modelSlug: 'model-y',
    year: 2025,
    trimName: 'Performance',
    caTrimName: 'Performance',
    driveType: 'AWD',
    basePriceMSRP: 55990,
    destinationFee: 1640,
    federalTaxCredit: 7500,
    effectivePrice: 50130,
    rangeEPA: 306,
    caRangeEPAkm: 494,
    acceleration060: '3.3',
    caAcceleration0100: '3.7',
    topSpeed: 155,
    horsepower: 510,
    torque: 527,
    batteryCapacity: '79',
    superchargerRateMax: 250,
    onboardCharger: '11.5',
    seatingCapacity: 5,
    cargoVolume: '76',
    towingCapacity: 3500,
    groundClearance: '6.6',
    displaySize: '15.4"',
    hasRearDisplay: true,
    wheelbase: '113.8',
    length: '187.0',
    width: '75.6',
    height: '63.9',
    curbWeight: 4416,
    mpge: 113,
    isCurrentModel: true,
    keyChangesFromPriorYear:
      'Juniper Performance: 510hp dual motor, Carbon fiber spoiler standard, and Track Mode 3.0. Current US spec is listed at 3.3s 0-60 and 306 miles EPA.',
    prosAndCons: {
      pros: [
        '3.3s 0-60 — fastest Model Y ever',
        '510hp dual motor',
        '306-mile EPA range',
        'Track Mode 3.0',
        'Juniper interior with rear screen',
      ],
      cons: [
        '$55,990 base — most expensive current MY',
        'Firm performance suspension',
        'Performance tires costly to replace',
        '21" wheels less practical in winter',
      ],
    },
  },
] as const;

async function seedVehicles() {
  const db = await getDb();

  try {
    // Upsert tesla models
    let insertedModels = 0;
    const modelIdMap = new Map<string, number>();

    for (const model of TESLA_MODELS) {
      const existing = await db
        .select({ id: teslaModel.id })
        .from(teslaModel)
        .where(eq(teslaModel.slug, model.slug))
        .limit(1);

      const modelData = {
        name: model.name,
        tagline: model.tagline,
        description: 'description' in model ? model.description : undefined,
        bodyType: model.bodyType,
        productionStart: model.productionStart,
        productionEnd:
          'productionEnd' in model ? model.productionEnd : undefined,
        isActive: model.isActive,
        sortOrder: model.sortOrder,
        seoTitle: 'seoTitle' in model ? model.seoTitle : undefined,
        seoDescription:
          'seoDescription' in model ? model.seoDescription : undefined,
      };

      if (existing.length > 0) {
        await db
          .update(teslaModel)
          .set({ ...modelData, updatedAt: new Date() })
          .where(eq(teslaModel.slug, model.slug));
        modelIdMap.set(model.slug, existing[0].id);
      } else {
        const result = await db
          .insert(teslaModel)
          .values({ ...modelData, slug: model.slug })
          .returning({ id: teslaModel.id });
        modelIdMap.set(model.slug, result[0].id);
        insertedModels++;
      }
    }

    console.log(
      `Tesla models: ${insertedModels} inserted, ${TESLA_MODELS.length - insertedModels} updated`
    );

    // Upsert vehicles
    let insertedVehicles = 0;
    let updatedVehicles = 0;

    for (const v of VEHICLES) {
      const modelId = modelIdMap.get(v.modelSlug);
      if (!modelId) {
        console.error(`Model not found for slug: ${v.modelSlug}`);
        continue;
      }

      const existing = await db
        .select({ id: vehicle.id })
        .from(vehicle)
        .where(eq(vehicle.slug, v.slug))
        .limit(1);

      const vehicleData = {
        title: v.title,
        modelId,
        year: v.year,
        trimName: v.trimName,
        caTrimName: ('caTrimName' in v ? v.caTrimName : undefined) as
          | string
          | undefined,
        driveType: v.driveType,
        basePriceMSRP: 'basePriceMSRP' in v ? v.basePriceMSRP : undefined,
        destinationFee: 'destinationFee' in v ? v.destinationFee : undefined,
        federalTaxCredit:
          'federalTaxCredit' in v ? v.federalTaxCredit : undefined,
        effectivePrice: 'effectivePrice' in v ? v.effectivePrice : undefined,
        rangeEPA: 'rangeEPA' in v ? v.rangeEPA : undefined,
        caRangeEPAkm: ('caRangeEPAkm' in v
          ? v.caRangeEPAkm
          : 'rangeEPA' in v && typeof v.rangeEPA === 'number'
            ? miToKm(v.rangeEPA)
            : undefined) as number | undefined,
        acceleration060: 'acceleration060' in v ? v.acceleration060 : undefined,
        caAcceleration0100: ('caAcceleration0100' in v
          ? v.caAcceleration0100
          : undefined) as string | undefined,
        topSpeed: 'topSpeed' in v ? v.topSpeed : undefined,
        caTopSpeedKmh: ('caTopSpeedKmh' in v
          ? v.caTopSpeedKmh
          : 'topSpeed' in v && typeof v.topSpeed === 'number'
            ? mphToKmh(v.topSpeed)
            : undefined) as number | undefined,
        horsepower: 'horsepower' in v ? v.horsepower : undefined,
        caHorsepower: ('caHorsepower' in v ? v.caHorsepower : undefined) as
          | number
          | undefined,
        torque: 'torque' in v ? v.torque : undefined,
        batteryCapacity: 'batteryCapacity' in v ? v.batteryCapacity : undefined,
        superchargerRateMax:
          'superchargerRateMax' in v ? v.superchargerRateMax : undefined,
        caSuperchargerRateMax: ('caSuperchargerRateMax' in v
          ? v.caSuperchargerRateMax
          : undefined) as number | undefined,
        onboardCharger: 'onboardCharger' in v ? v.onboardCharger : undefined,
        seatingCapacity: 'seatingCapacity' in v ? v.seatingCapacity : undefined,
        displaySize: 'displaySize' in v ? v.displaySize : undefined,
        hasRearDisplay: 'hasRearDisplay' in v ? v.hasRearDisplay : undefined,
        wheelbase: 'wheelbase' in v ? v.wheelbase : undefined,
        length: 'length' in v ? v.length : undefined,
        width: 'width' in v ? v.width : undefined,
        height: 'height' in v ? v.height : undefined,
        curbWeight: 'curbWeight' in v ? v.curbWeight : undefined,
        cargoVolume: 'cargoVolume' in v ? v.cargoVolume : undefined,
        towingCapacity: 'towingCapacity' in v ? v.towingCapacity : undefined,
        groundClearance: 'groundClearance' in v ? v.groundClearance : undefined,
        mpge: 'mpge' in v ? v.mpge : undefined,
        prosAndCons:
          'prosAndCons' in v && v.prosAndCons
            ? { pros: [...v.prosAndCons.pros], cons: [...v.prosAndCons.cons] }
            : undefined,
        keyChangesFromPriorYear:
          'keyChangesFromPriorYear' in v
            ? v.keyChangesFromPriorYear
            : undefined,
        isCurrentModel: v.isCurrentModel,
        caAvailable: ('caAvailable' in v ? v.caAvailable : true) as boolean,
      };

      if (existing.length > 0) {
        await db
          .update(vehicle)
          .set({ ...vehicleData, lastUpdated: new Date() })
          .where(eq(vehicle.slug, v.slug));
        updatedVehicles++;
      } else {
        await db.insert(vehicle).values({ ...vehicleData, slug: v.slug });
        insertedVehicles++;
      }
    }

    console.log(
      `Vehicles: ${insertedVehicles} inserted, ${updatedVehicles} updated`
    );
    console.log(`Total vehicles in seed: ${VEHICLES.length}`);
    console.log('Seed completed successfully');
  } catch (error) {
    console.error('Seed failed:', error);
    throw error;
  }

  process.exit(0);
}

seedVehicles();
